name: Karma
version: '0.1.1'
main: my.consler.karma.karma.Main
api-version: '1.21'
authors: [ Consler ]
description: A plugin to give players positive or negative effects for good and bad actions accordingly.

commands:
  checkKarma:
    description: Check one's karma
    usage:  §CCorrect usage is /checkkarma <player> OR /checkkarma
    permission: Karma.default
  thank:
    description: Thank someone with karma
    usage: §CCorrect usage is /thank <player>
    permission: Karma.default
  setKarma:
    description: Set one's karma
    usage: §CCorrect usage is /setkarma <player> <number> OR /setkarma <number>
    permission: Karma.op

permissions:
  Karma.default:
    default: true
  Karma.op:
    default: op